repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:3.0.1
  javax_javaee: javax:javaee-api:jar:7.0

  eclipselink: org.eclipse.persistence:eclipselink:jar:2.5.1
  h2db: com.h2database:h2:jar:1.3.159
